name: video_demo
description: A Flutter project to manage video.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  scrollable_positioned_list: ^0.3.2
  video_player: ^2.4.2
  wakelock: ^0.6.1+2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1

flutter_gen:
  output: lib/assets/

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
