name: video_demo
description: A Flutter project to manage video.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  freezed: ^1.1.1
  hooks_riverpod: ^1.0.3
  video_player: ^2.2.19

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed_annotation: ^1.1.0

flutter_gen:
  output: lib/assets/

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
